apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.4.0 (c7964e7)
  creationTimestamp: null
  labels:
    io.kompose.service: spring-boot-k8
  name: spring-boot-k8
spec:
  ports:
  - name: "9085"
    port: 9085
    targetPort: 9085
  selector:
    io.kompose.service: spring-boot-k8
status:
  loadBalancer: {}
