apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.4.0 (c7964e7)
  creationTimestamp: null
  labels:
    io.kompose.service: spring-boot-k8
  name: spring-boot-k8
spec:
  replicas: 1
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: spring-boot-k8
    spec:
      containers:
      - image: spring-boot-k8
        name: spring-boot-k8
        ports:
        - containerPort: 9085
        resources: {}
      restartPolicy: Always
status: {}
